[project]
name = "belhisfirm-belhishaai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.13.0",
    "bitsandbytes>=0.49.2",
    "ninja>=1.13.0",
    "numpy>=2.4.1",
    "nvidia-nccl-cu13>=2.29.7",
    "opencv-python>=4.13.0.90",
    "pypdf2>=3.0.1",
    "pytesseract>=0.3.13",
    "reportlab>=4.4.10",
    "surya-ocr>=0.17.1",
    "textual>=7.3.0",
    "torch==2.9.1",
    "torchvision>=0.24.1",
    "transformers==4.57.3",
    "ultralytics>=8.4.37",
    "wand>=0.7.0",
]
