[project]
name = "belhisfirm-belhishaai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.13.0",
    "ninja>=1.13.0",
    "numpy>=2.4.1",
    "nvidia-nccl-cu13>=2.29.7",
    "opencv-python>=4.13.0.90",
    "openai>=3.3.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.2",
    "pypdf2>=3.0.1",
    "reportlab>=4.4.10",
    "requests>=2.32.0",
    "scikit-learn>=1.8.0",
    "sklearn-crfsuite>=0.5.0",
    "surya-ocr==0.17.1",
    "textual>=8.2.8",
    "textualeffects>=0.2.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "transformers>=5.17.0",
    "ultralytics>=8.4.37",
    "wand>=0.7.0",
    "geoparser>=0.3.1",
    "text2num>=3.1.0",
]
